services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    ports:
      - 1894:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=linkwarden
      - POSTGRES_USER=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - linkwarden-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/linkwarden?schema=public
      - NEXTAUTH_URL=http://localhost:1895
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - MEILI_URL=http://meilisearch:7700
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - PORT=3100
    restart: always
    image: ghcr.io/linkwarden/linkwarden:latest
    ports:
      - 1895:3100
    volumes:
      - ./data:/data/data
    depends_on:
      postgres:
        condition: service_healthy
      meilisearch:
        condition: service_started
    networks:
      - linkwarden-network
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: always
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    ports:
      - 1896:7700
    env_file:
      - .env
    volumes:
      - ./meili_data:/meili_data
    networks:
      - linkwarden-network

networks:
  linkwarden-network:
    driver: bridge
