services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    ports:
      - 1894:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:1894/postgres
    restart: always
    # build: . # uncomment to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment to build from source
    ports:
      - 1895:1895
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
      - meilisearch
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: always
    ports:
      - 1896:1896
    env_file:
      - .env
    volumes:
      - ./meili_data:/meili_data
